name: Build and deploy Node.js app to Azure Web App - Hillenbrand-ADT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Debug - Repository Structure
      run: |
        pwd
        ls -la
        echo "Current directory contents:"
        find . -maxdepth 2 -type f
    
    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    
    - name: Update Git Configuration
      run: |
        git config --global user.name "showbhik4u"
        git config --global user.email "showbhik.goswamy@gmail.com"
    
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Dependencies
      run: npm ci
    
    - name: List package-lock.json
      run: |
        ls -l package-lock.json
        cat package-lock.json
    
    - name: Build
      run: npm run build
    
    - name: Zip artifact for deployment
      run: zip release.zip ./* -r
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
    
    - name: Unzip artifact for deployment
      run: unzip release.zip
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69B217E273BC4C9AB377C01FFEAD5C1A }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6658EDC34E4D4D0D9B1AEA850716410E }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F00C1F66AB1C447680309DF390867FA8 }}
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Hillenbrand-ADT'
        slot-name: 'Production'
        package: .
    
    - name: Debug - Git Configuration
      run: |
        git config --list
        git submodule foreach --recursive git config --list